# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Sqorz Documentation
site_url: https://mydomain.org/mysite
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
