# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Sqorz Documentation
site_url: https://mydomain.org
theme:
  name: material
  logo: eventsoft.png
  features:
    - navigation.tabs
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md